server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 9000
spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    # 建表策略false强制校验，true表不存在则创建
    database-schema-update: true
    # 关闭每次启动时候自动部署
    deployment-mode: never-fail
    # 关闭自动部署验证
    check-process-definitions: false
    db-history-used: true
logging:
  level:
    root: info