spring:
  datasource:
    url: jdbc:postgresql://192.168.187.130:5432/postgres
    username: postgres
    password: 5545955
    driver-class-name: org.postgresql.Driver
liquibase:
    options: ROLLBACK
    tags: v1.0
